name: CI
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 3 * * 1'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYPI_URL: https://:${{ secrets.ECHO_LIBRARIES_ACCESS_KEY }}@pypi.echohq.com/simple

jobs:

  linting:
      name: Check Python version compatibility
      runs-on: cx-public-ubuntu-x64
      strategy:
        max-parallel: 3
        matrix:
          pver:
            - "3.10"
            - "3.11"
            - "3.12"
            - "3.13"
            - "3.14"
      steps:
        - name: Fetch Code
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
          with:
            persist-credentials: false

        - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
          with:
            python-version: ${{ matrix.pver }}

        - name: Install Pylint
          shell: bash
          run: |
            pip config set global.index-url ${PYPI_URL}
            pip install pylint .

        - name: Pylint
          shell: bash
          run: |
            pylint --disable=all --enable=E,F --disable=E1121 --score=false src

        - name: Compile
          shell: bash
          run: |
            python -m compileall src tests

        - name: Check docstrings
          shell: bash
          run: |
            cxone-repo-tools -h

  execute-unit-tests:
    name: Unit Tests
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'

      - name: Install packages
        run: |
          pip config set global.index-url ${PYPI_URL}
          pip install pytest .

      - name: Execute Unit Tests
        run: |
          . .env
          python -m unittest discover -v -p test_*.py -s ${GITHUB_WORKSPACE}/tests

  check-format:
    name: Code format enforcement
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'

      - name: Check formatting
        run: |
          pip config set global.index-url ${PYPI_URL}
          pip install black==26.5.1
          black --target-version py312 --check .

  build-wheel:
    name: Call
    uses: ./.github/workflows/build-whl.yml
    secrets:
      ECHO_LIBRARIES_ACCESS_KEY: ${{ secrets.ECHO_LIBRARIES_ACCESS_KEY }}
    with:
      buildonly: true
  
  build-docs:
    name: Call
    uses: ./.github/workflows/build-docs.yml
    secrets:
      ECHO_LIBRARIES_ACCESS_KEY: ${{ secrets.ECHO_LIBRARIES_ACCESS_KEY }}
    with:
      buildonly: true      